import React, { useState, useMemo, useRef, useEffect } from 'react';
import { 
  Plus, X, Settings2, BarChart2, Layers, Download, Search, ChevronDown, ChevronRight, Check
} from 'lucide-react';
import {
  ComposedChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Legend
} from 'recharts';
import { exportToCSV } from '../utils/export';
import { getConstantColor } from '../utils/colors';

export default function ProWorkspace({ db, treeGroupedDatasets }) {
  const [layers, setLayers] = useState([]);
  const [layerIdCounter, setLayerIdCounter] = useState(1);
  const [collapsedLayers, setCollapsedLayers] = useState({});
  const [isCatalogOpen, setIsCatalogOpen] = useState(false);
  const [catalogSearch, setCatalogSearch] = useState('');
  const [collapsedCatalogGroups, setCollapsedCatalogGroups] = useState({});

  // Add a new empty layer from catalog
  const addLayer = (datasetId) => {
    const dataset = db.datasets.find(d => d.id === datasetId);
    const initialFilters = {};
    
    if (dataset) {
      const otherDims = dataset.originalData.structure.dimensions.filter(d => d.code !== 'PERIOD');
      otherDims.forEach(d => {
        const totalItem = d.items.find(i => i.id === 'T' || i.name?.lang_ru?.toLowerCase().includes('всего') || i.name?.lang_ru?.toLowerCase().includes('оба пола'));
        initialFilters[d.code] = [totalItem ? totalItem.id : d.items[0]?.id];
      });
    }

    setLayers([...layers, {
      id: layerIdCounter,
      datasetId: datasetId,
      filters: initialFilters,
      yAxisId: 'left', // left or right
      type: 'line', // line or bar
      name: dataset?.title || `Слой ${layerIdCounter}`
    }]);
    setLayerIdCounter(prev => prev + 1);
  };

  const removeLayer = (id) => {
    setLayers(layers.filter(l => l.id !== id));
  };

  const updateLayer = (id, updates) => {
    setLayers(layers.map(l => l.id === id ? { ...l, ...updates } : l));
  };

  const toggleLayerCollapse = (id) => {
    setCollapsedLayers(prev => ({ ...prev, [id]: !prev[id] }));
  };

  // Compile data from all layers into a single time series with multi-selection expansion
  const { chartData, seriesList } = useMemo(() => {
    if (layers.length === 0) return { chartData: [], seriesList: [] };
    
    const yearMap = {};
    const allSeries = [];

    layers.forEach((layer) => {
      const dataset = db.datasets.find(d => d.id === layer.datasetId);
      if (!dataset) return;

      const { originalData } = dataset;
      const dims = originalData.structure.dimensions;
      const periodDim = dims.find(d => d.code === 'PERIOD');
      const otherDims = dims.filter(d => d.code !== 'PERIOD');
      if (!periodDim) return;

      // Extract normalized filters (each dimension code maps to an array of selected item IDs)
      const currentFilters = {};
      otherDims.forEach(d => {
        const raw = layer.filters?.[d.code];
        if (Array.isArray(raw) && raw.length > 0) {
          currentFilters[d.code] = raw;
        } else if (typeof raw === 'string' && raw) {
          currentFilters[d.code] = [raw];
        } else {
          const totalItem = d.items.find(i => i.id === 'T' || i.name?.lang_ru?.toLowerCase().includes('всего') || i.name?.lang_ru?.toLowerCase().includes('оба пола'));
          currentFilters[d.code] = [totalItem ? totalItem.id : d.items[0]?.id];
        }
      });

      // Generate Cartesian product of selected filter items across all non-period dimensions
      let combinations = [{}];
      otherDims.forEach(d => {
        const selectedIds = currentFilters[d.code];
        const nextCombos = [];
        combinations.forEach(combo => {
          selectedIds.forEach(id => {
            nextCombos.push({ ...combo, [d.code]: id });
          });
        });
        combinations = nextCombos;
      });

      // Total series generated by this layer
      const totalCombos = combinations.length;

      // For each combination, construct a distinct series
      combinations.forEach((combo) => {
        const comboKey = otherDims.map(d => combo[d.code]).join('_');
        const seriesKey = `Layer_${layer.id}_${comboKey}`;

        // Build human-friendly label
        const labelParts = [];
        otherDims.forEach(d => {
          const item = d.items.find(i => i.id === combo[d.code]);
          const itemName = item?.name?.lang_ru || combo[d.code];
          
          // If this dimension has multiple items selected, ALWAYS include its label
          if (currentFilters[d.code].length > 1) {
            labelParts.push(itemName);
          } else if (totalCombos === 1) {
            // If only 1 combination in total, only show if not default "Все" / "Республика Беларусь"
            const isTotal = item?.id === 'T' || itemName.toLowerCase().includes('все') || itemName.toLowerCase().includes('республика беларусь');
            if (!isTotal) {
              labelParts.push(itemName);
            }
          }
        });

        const seriesName = labelParts.length > 0 
          ? `${layer.name} (${labelParts.join(', ')})`
          : layer.name;

        allSeries.push({
          key: seriesKey,
          name: seriesName,
          layerId: layer.id,
          yAxisId: layer.yAxisId || 'left',
          color: getConstantColor(seriesName)
        });

        // Extract time series points for this combination
        periodDim.items.forEach(period => {
          const year = period.name?.lang_ru || period.id;
          
          const keyParts = dims.map(d => {
            if (d.code === 'PERIOD') return period.id;
            return combo[d.code];
          });
          const key = keyParts.join(':');
          const val = originalData.dataset[key];
          
          if (val !== undefined && val !== null && val !== '-') {
            const numVal = parseFloat(val);
            if (!isNaN(numVal)) {
              if (!yearMap[year]) yearMap[year] = { year, numericYear: parseInt(year, 10) };
              yearMap[year][seriesKey] = numVal;
            }
          }
        });
      });
    });

    // Convert map to sorted array
    const sortedData = Object.values(yearMap).sort((a, b) => a.numericYear - b.numericYear);
    return { chartData: sortedData, seriesList: allSeries };
  }, [layers, db]);

  // Custom Legend formatter
  const renderLegend = (value) => {
    const s = seriesList.find(item => item.key === value);
    return <span className="text-xs font-semibold ml-1 text-slate-700">{s ? s.name : value}</span>;
  };

  return (
    <div className="flex h-full overflow-hidden bg-slate-100 relative">
      {/* Layers Panel (Left) */}
      <div className="w-84 bg-slate-900 border-r border-slate-800 shadow-xl flex flex-col z-10 shrink-0 h-full overflow-y-auto">
        <div className="p-4 border-b border-slate-800 bg-slate-900/95 text-white flex justify-between items-center sticky top-0 z-20 backdrop-blur-sm">
          <div className="flex items-center space-x-2">
            <Layers size={20} className="text-amber-400" />
            <h2 className="font-bold tracking-wide uppercase text-sm">Слои данных</h2>
          </div>
          <button 
            onClick={() => setIsCatalogOpen(true)}
            className="p-1.5 hover:bg-slate-800 text-slate-300 hover:text-white rounded-md transition-colors border border-slate-700 hover:border-slate-600 shadow-xs cursor-pointer"
            title="Добавить показатель"
          >
            <Plus size={16} />
          </button>
        </div>

        <div className="p-4 space-y-4">
          {layers.length === 0 ? (
            <div className="text-center p-8 text-slate-500 text-sm border-2 border-dashed border-slate-700 rounded-xl bg-slate-800/50">
              <Layers size={32} className="mx-auto mb-3 text-slate-600" />
              Слои не добавлены
            </div>
          ) : (
            layers.map((layer) => (
              <LayerConfigCard 
                key={layer.id} 
                layer={layer} 
                db={db} 
                onUpdate={(updates) => updateLayer(layer.id, updates)}
                onRemove={() => removeLayer(layer.id)}
                isCollapsed={collapsedLayers[layer.id]}
                onToggleCollapse={() => toggleLayerCollapse(layer.id)}
                color={getConstantColor(layer.name)}
              />
            ))
          )}
        </div>
      </div>

      {/* Main Chart Area (Right) */}
      <div className="flex-1 p-4 sm:p-6 overflow-y-auto">
        <div className="bg-white rounded-2xl shadow-sm border border-slate-200 p-6 flex flex-col h-full min-h-[500px]">
          <div className="flex justify-between items-start mb-6">
            <div>
              <h2 className="text-xl font-bold text-slate-900 tracking-tight">Мульти-анализ показателей</h2>
              <p className="text-xs text-slate-500 mt-1">Сравнение различных срезов, категорий и показателей на одной шкале</p>
            </div>
            {chartData.length > 0 && (
              <button 
                onClick={() => {
                  const exportRows = chartData.map(row => {
                    const formatted = { "Год": row.year };
                    seriesList.forEach(s => {
                      formatted[s.name] = row[s.key] !== undefined ? row[s.key] : '';
                    });
                    return formatted;
                  });
                  const headers = ["Год", ...seriesList.map(s => s.name)];
                  exportToCSV(exportRows, headers, 'pro_multivariate_analysis');
                }}
                className="bg-amber-500 hover:bg-amber-600 text-white px-4 py-2 rounded-lg text-xs font-bold transition-colors flex items-center shadow-sm cursor-pointer"
              >
                <Download size={16} className="mr-2" />
                Экспорт CSV
              </button>
            )}
          </div>

          <div className="flex-1 min-h-0 w-full" tabIndex={-1}>
            {chartData.length > 0 && seriesList.length > 0 ? (
              <ResponsiveContainer width="100%" height="100%" minWidth={0} debounce={50}>
                <ComposedChart data={chartData} margin={{ top: 20, right: 30, left: 10, bottom: 20 }}>
                  <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#f1f5f9" />
                  <XAxis dataKey="year" tick={{fill: '#64748b', fontSize: 12}} tickLine={false} axisLine={{stroke: '#cbd5e1'}} />
                  <YAxis 
                    yAxisId="left" 
                    orientation="left" 
                    tick={{fill: '#64748b', fontSize: 12}} 
                    tickLine={false} 
                    axisLine={false} 
                    width={70}
                    tickFormatter={val => new Intl.NumberFormat('ru-RU', { notation: "compact" }).format(val)}
                  />
                  <YAxis 
                    yAxisId="right" 
                    orientation="right" 
                    tick={{fill: '#64748b', fontSize: 12}} 
                    tickLine={false} 
                    axisLine={false} 
                    width={70}
                    tickFormatter={val => new Intl.NumberFormat('ru-RU', { notation: "compact" }).format(val)}
                  />
                  <Tooltip 
                    wrapperStyle={{ pointerEvents: 'none', outline: 'none' }}
                    contentStyle={{borderRadius: '12px', border: '1px solid #334155', backgroundColor: 'rgba(15, 23, 42, 0.95)', color: 'white', fontSize: '12px', backdropFilter: 'blur(8px)', pointerEvents: 'none'}}
                    formatter={(value, name) => {
                      const s = seriesList.find(item => item.key === name);
                      return [new Intl.NumberFormat('ru-RU').format(value), s ? s.name : name];
                    }}
                    labelStyle={{color: '#94a3b8', fontWeight: 'bold', marginBottom: '8px', borderBottom: '1px solid #334155', paddingBottom: '4px'}}
                  />
                  <Legend formatter={renderLegend} iconType="circle" wrapperStyle={{paddingTop: '20px'}} />
                  
                  {seriesList.map((series) => (
                    <Line
                      key={series.key}
                      yAxisId={series.yAxisId}
                      type="monotone"
                      dataKey={series.key}
                      name={series.name}
                      stroke={series.color}
                      strokeWidth={3}
                      isAnimationActive={false}
                      dot={{ r: 4, strokeWidth: 1, stroke: '#fff', fill: series.color }}
                      activeDot={{ r: 6, strokeWidth: 2, stroke: '#fff' }}
                      connectNulls
                    />
                  ))}
                </ComposedChart>
              </ResponsiveContainer>
            ) : (
                <div className="h-full flex flex-col items-center justify-center bg-slate-50/50 rounded-2xl text-slate-400 border-2 border-dashed border-slate-200">
                   <BarChart2 size={64} className="text-slate-200 mb-4" />
                   <p className="text-base font-semibold text-slate-600">Нет данных для отображения</p>
                </div>
            )}
          </div>
        </div>
      </div>

      {/* Catalog Modal */}
      {isCatalogOpen && (
        <div className="absolute inset-0 bg-slate-900/60 backdrop-blur-sm z-50 flex items-center justify-center p-4 sm:p-6">
          <div className="bg-white rounded-2xl shadow-2xl flex flex-col w-full max-w-5xl max-h-full overflow-hidden border border-slate-200">
            {/* Header */}
            <div className="p-4 border-b border-slate-100 flex justify-between items-center bg-slate-50/50 shrink-0">
              <div className="flex items-center space-x-3">
                <div className="bg-blue-100 p-2 rounded-lg">
                  <Layers className="text-blue-600" size={20} />
                </div>
                <div>
                  <h3 className="text-lg font-bold text-slate-900">Каталог данных</h3>
                </div>
              </div>
              <button 
                onClick={() => setIsCatalogOpen(false)}
                className="p-2 hover:bg-slate-200 rounded-full text-slate-500 transition-colors cursor-pointer"
              >
                <X size={22} />
              </button>
            </div>
            
            {/* Search */}
            <div className="p-4 border-b border-slate-100 bg-white shrink-0">
              <div className="relative">
                <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={18} />
                <input 
                  type="text"
                  placeholder="Поиск по показателям..."
                  value={catalogSearch}
                  onChange={(e) => setCatalogSearch(e.target.value)}
                  className="w-full pl-10 pr-4 py-2.5 bg-slate-50 border border-slate-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500/50 focus:border-blue-500 transition-all font-medium text-slate-700"
                />
              </div>
            </div>

            {/* List with Categories */}
            <div className="flex-1 overflow-y-auto p-4 bg-slate-50 space-y-6">
              {treeGroupedDatasets.map(group => {
                const GroupIcon = group.icon;
                const filteredItems = group.items.filter(ds => 
                  ds.title.toLowerCase().includes(catalogSearch.toLowerCase())
                );
                
                if (filteredItems.length === 0) return null;
                const isGroupCollapsed = collapsedCatalogGroups[group.id] ?? true;

                return (
                  <div key={group.id} className="mb-4 bg-white rounded-xl border border-slate-200 overflow-hidden shadow-sm">
                    <button 
                      onClick={() => setCollapsedCatalogGroups(prev => ({...prev, [group.id]: !isGroupCollapsed}))}
                      className="w-full px-4 py-3 flex items-center justify-between bg-slate-50 hover:bg-slate-100 transition-colors cursor-pointer"
                    >
                      <div className="flex items-center space-x-2">
                        <GroupIcon size={18} className="text-blue-500" />
                        <span className="text-sm font-bold text-slate-700 uppercase tracking-wider">{group.title}</span>
                      </div>
                      {isGroupCollapsed ? <ChevronRight size={18} className="text-slate-400" /> : <ChevronDown size={18} className="text-slate-400" />}
                    </button>
                    
                    {!isGroupCollapsed && (
                      <div className="p-2 space-y-1 bg-white">
                        {filteredItems.map(ds => {
                          const addedLayer = layers.find(l => l.datasetId === ds.id);
                          const isAdded = !!addedLayer;
                          return (
                            <button
                              key={ds.id}
                              onClick={() => {
                                if (isAdded) {
                                  removeLayer(addedLayer.id);
                                } else {
                                  addLayer(ds.id);
                                }
                              }}
                              className={`w-full text-left p-3.5 rounded-xl transition-all border group flex items-center justify-between cursor-pointer ${
                                isAdded 
                                  ? 'bg-emerald-50/50 border-emerald-300' 
                                  : 'bg-white border-transparent hover:border-slate-200 hover:shadow-xs hover:bg-slate-50'
                              }`}
                            >
                              <div className="pr-4 flex-1">
                                <h5 className={`font-bold transition-colors leading-snug ${isAdded ? 'text-emerald-900' : 'text-slate-800 group-hover:text-blue-600'}`}>{ds.title}</h5>
                                <p className={`text-[11px] mt-1 uppercase tracking-wider ${isAdded ? 'text-emerald-700/70' : 'text-slate-400'}`}>{ds.source}</p>
                              </div>
                              <div className="shrink-0 flex items-center justify-center p-1">
                                <Plus 
                                  size={24} 
                                  className={`transition-all duration-200 ease-in-out shrink-0 ${
                                    isAdded 
                                      ? 'text-red-500 rotate-45 hover:text-red-600 hover:scale-110' 
                                      : 'text-slate-400 rotate-0 group-hover:text-blue-600'
                                  }`} 
                                />
                              </div>
                            </button>
                          );
                        })}
                      </div>
                    )}
                  </div>
                );
              })}
              
              {treeGroupedDatasets.every(group => 
                group.items.filter(ds => ds.title.toLowerCase().includes(catalogSearch.toLowerCase())).length === 0
              ) && (
                <div className="text-center py-12 text-slate-400">
                  Ничего не найдено по вашему запросу.
                </div>
              )}
            </div>

            {/* Footer with Done Button */}
            <div className="p-4 border-t border-slate-100 bg-white shrink-0 flex justify-end">
               <button 
                  onClick={() => setIsCatalogOpen(false)}
                  className="bg-blue-600 hover:bg-blue-700 text-white font-bold py-2.5 px-6 rounded-xl transition-colors shadow-md hover:shadow-lg cursor-pointer"
               >
                 Готово
               </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

function MultiSelectDropdown({ label, items, selectedValues, onChange }) {
  const [isOpen, setIsOpen] = useState(false);
  const [search, setSearch] = useState('');
  const dropdownRef = useRef(null);

  // Close popover when clicking outside
  useEffect(() => {
    function handleClickOutside(event) {
      if (dropdownRef.current && !dropdownRef.current.contains(event.target)) {
        setIsOpen(false);
      }
    }
    if (isOpen) {
      document.addEventListener('mousedown', handleClickOutside);
      return () => document.removeEventListener('mousedown', handleClickOutside);
    }
  }, [isOpen]);

  const allItemIds = useMemo(() => items.map(i => i.id), [items]);
  const isAllSelected = items.length > 0 && selectedValues.length === items.length;

  const toggleItem = (id) => {
    let next;
    if (selectedValues.includes(id)) {
      if (selectedValues.length === 1) return; // Prevent unselecting all (keep at least 1)
      next = selectedValues.filter(v => v !== id);
    } else {
      next = [...selectedValues, id];
    }
    onChange(next);
  };

  const selectAll = () => {
    onChange([...allItemIds]);
  };

  const selectOnlyDefault = () => {
    const totalItem = items.find(i => i.id === 'T' || i.name?.lang_ru?.toLowerCase().includes('всего') || i.name?.lang_ru?.toLowerCase().includes('оба пола'));
    onChange([totalItem ? totalItem.id : items[0]?.id]);
  };

  const filteredItems = useMemo(() => {
    if (!search.trim()) return items;
    return items.filter(i => (i.name?.lang_ru || i.id).toLowerCase().includes(search.toLowerCase()));
  }, [items, search]);

  // Display text in the trigger button
  const summaryText = useMemo(() => {
    if (!selectedValues || selectedValues.length === 0) return 'Выберите...';
    if (isAllSelected) return `Все (${items.length})`;
    if (selectedValues.length === 1) {
      const it = items.find(i => i.id === selectedValues[0]);
      return it?.name?.lang_ru || selectedValues[0];
    }
    const names = selectedValues.map(v => {
      const it = items.find(i => i.id === v);
      return it?.name?.lang_ru || v;
    });
    if (selectedValues.length <= 2) {
      return names.join(', ');
    }
    return `Выбрано: ${selectedValues.length} из ${items.length}`;
  }, [selectedValues, isAllSelected, items]);

  return (
    <div className="relative" ref={dropdownRef}>
      <label className="block text-[10px] font-bold text-slate-400 uppercase tracking-wider mb-1.5 truncate" title={label}>
        {label}
      </label>
      
      {/* Trigger Button */}
      <button
        type="button"
        onClick={() => setIsOpen(!isOpen)}
        className={`w-full bg-slate-900 border text-slate-200 rounded-lg px-3 py-2 text-xs flex items-center justify-between gap-2 outline-none transition-all cursor-pointer text-left shadow-xs ${
          isOpen ? 'border-amber-500 ring-1 ring-amber-500' : 'border-slate-700 hover:border-slate-600'
        }`}
      >
        <span className="truncate font-medium text-slate-200 text-xs">{summaryText}</span>
        <div className="flex items-center space-x-1.5 shrink-0">
          {selectedValues.length > 1 && !isAllSelected && (
            <span className="bg-blue-600/40 text-blue-300 text-[10px] px-1.5 py-0.5 rounded-full font-bold border border-blue-500/30">
              +{selectedValues.length}
            </span>
          )}
          {isAllSelected && items.length > 1 && (
            <span className="bg-emerald-600/40 text-emerald-300 text-[10px] px-1.5 py-0.5 rounded-full font-bold border border-emerald-500/30">
              Все
            </span>
          )}
          <ChevronDown size={14} className={`text-slate-400 transition-transform ${isOpen ? 'rotate-180 text-amber-400' : ''}`} />
        </div>
      </button>

      {/* Popover */}
      {isOpen && (
        <div className="absolute left-0 right-0 top-full mt-1 bg-slate-900 border border-slate-700 rounded-xl shadow-2xl z-50 overflow-hidden flex flex-col max-h-60">
          {/* Quick Actions Header */}
          <div className="p-2 bg-slate-950 border-b border-slate-800 flex items-center justify-between text-[11px] font-semibold shrink-0">
            <button
              type="button"
              onClick={selectAll}
              className="text-blue-400 hover:text-blue-300 px-2 py-0.5 rounded hover:bg-slate-800 transition-colors cursor-pointer"
            >
              Выбрать все
            </button>
            <button
              type="button"
              onClick={selectOnlyDefault}
              className="text-slate-400 hover:text-slate-300 px-2 py-0.5 rounded hover:bg-slate-800 transition-colors cursor-pointer"
            >
              Сбросить
            </button>
          </div>

          {/* Search if > 5 items */}
          {items.length > 5 && (
            <div className="p-2 border-b border-slate-800 bg-slate-900 shrink-0">
              <input
                type="text"
                placeholder="Поиск..."
                value={search}
                onChange={e => setSearch(e.target.value)}
                className="w-full bg-slate-950 border border-slate-800 rounded-lg px-2.5 py-1 text-xs text-slate-200 placeholder-slate-500 focus:outline-none focus:border-amber-500"
              />
            </div>
          )}

          {/* Items List */}
          <div className="overflow-y-auto p-1.5 space-y-0.5 flex-1">
            {filteredItems.map(item => {
              const isChecked = selectedValues.includes(item.id);
              return (
                <div
                  key={item.id}
                  onClick={() => toggleItem(item.id)}
                  className={`flex items-center space-x-2.5 px-2.5 py-1.5 rounded-lg text-xs cursor-pointer select-none transition-colors ${
                    isChecked 
                      ? 'bg-blue-950/60 text-blue-200 font-semibold' 
                      : 'text-slate-300 hover:bg-slate-800 hover:text-white'
                  }`}
                >
                  <div className={`w-4 h-4 rounded flex items-center justify-center border transition-colors shrink-0 ${
                    isChecked ? 'bg-blue-600 border-blue-500 text-white' : 'border-slate-600 bg-slate-800'
                  }`}>
                    {isChecked && <Check size={12} strokeWidth={3} />}
                  </div>
                  <span className="truncate flex-1">{item.name?.lang_ru || item.id}</span>
                </div>
              );
            })}
            {filteredItems.length === 0 && (
              <div className="text-center py-3 text-slate-500 text-xs">
                Ничего не найдено
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
}

function LayerConfigCard({ layer, db, onUpdate, onRemove, isCollapsed, onToggleCollapse, color }) {
  const dataset = db.datasets.find(d => d.id === layer.datasetId);
  const dims = dataset ? dataset.originalData.structure.dimensions.filter(d => d.code !== 'PERIOD') : [];

  return (
    <div className={`border border-slate-700 rounded-xl bg-slate-800 shadow-lg transition-all duration-200 ${isCollapsed ? 'opacity-80 hover:opacity-100' : ''}`}>
      <div 
        className={`p-2.5 text-xs font-bold text-white flex justify-between items-center relative cursor-pointer group select-none ${isCollapsed ? 'rounded-xl' : 'rounded-t-xl'}`}
        style={{ backgroundColor: color }}
        onClick={onToggleCollapse}
      >
        <div className="flex items-center space-x-2 truncate pr-2 w-full">
          {isCollapsed ? <ChevronRight size={16} className="opacity-70" /> : <ChevronDown size={16} className="opacity-70" />}
          <input 
            type="text" 
            value={layer.name} 
            onChange={(e) => onUpdate({ name: e.target.value })}
            onClick={(e) => e.stopPropagation()}
            className="bg-black/10 hover:bg-black/20 focus:bg-black/40 px-2 py-1 rounded outline-none border-none text-white placeholder:text-white/60 font-bold truncate w-full transition-colors cursor-text"
          />
        </div>
        <button 
          onClick={(e) => { e.stopPropagation(); onRemove(); }} 
          className="p-1.5 hover:bg-black/20 rounded-md z-10 shrink-0 transition-colors ml-2 opacity-0 group-hover:opacity-100 cursor-pointer"
          title="Удалить слой"
        >
          <X size={16} />
        </button>
      </div>
      
      {!isCollapsed && (
        <div className="p-4 space-y-4">
          <div className="text-xs font-bold text-slate-300 leading-snug mb-2 border-b border-slate-700/50 pb-2">
            {db.datasets.find(d => d.id === layer.datasetId)?.title}
          </div>

          {dims.map(dim => {
            const raw = layer.filters?.[dim.code];
            let selected = [];
            if (Array.isArray(raw)) {
              selected = raw;
            } else if (typeof raw === 'string' && raw) {
              selected = [raw];
            } else {
              const totalItem = dim.items.find(i => i.id === 'T' || i.name?.lang_ru?.toLowerCase().includes('всего') || i.name?.lang_ru?.toLowerCase().includes('оба пола'));
              selected = [totalItem ? totalItem.id : dim.items[0]?.id];
            }

            return (
              <MultiSelectDropdown
                key={dim.code}
                label={dim.name?.lang_ru || dim.code}
                items={dim.items}
                selectedValues={selected}
                onChange={(newValues) => {
                  onUpdate({
                    filters: {
                      ...layer.filters,
                      [dim.code]: newValues
                    }
                  });
                }}
              />
            );
          })}

          <div className="border-t border-slate-700/50 pt-3 mt-4 flex space-x-2">
            <div className="flex-1">
              <label className="block text-[10px] font-bold text-slate-400 uppercase tracking-wider mb-1.5">Привязка оси Y</label>
              <select 
                className="w-full bg-slate-900 border border-slate-700 text-slate-200 rounded-lg px-3 py-2 text-xs focus:ring-1 focus:ring-amber-500 focus:border-amber-500 outline-none transition-shadow cursor-pointer"
                value={layer.yAxisId}
                onChange={e => onUpdate({ yAxisId: e.target.value })}
              >
                <option value="left">Левая (Млн / Базовая)</option>
                <option value="right">Правая (Тыс / Проценты)</option>
              </select>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
